# tasks file for r
---
- name: Check r_version_35
  debug:
    msg: "[WARNING] r_version_35 variable is obsolete, you should use r_version now"
  when: r_version_35 is defined

- include: repository.yml
  tags:
    - configuration
    - r
    - r-repository

- include: install.yml
  tags:
    - configuration
    - r
    - r-install

- include: packages.yml
  tags:
    - configuration
    - r
    - r-packages
